### PR TITLE
Add product interface and generic Host and Vm pages

### PR DESCRIPTION
**Pull request by coltonw**

### CODE REVIEW

**Comment by goodmorninggoaway** [comment]
This can be done later: Add some unit test examples. Last time I checked, most of the microapps do minimal or no tests. This was probably 8 months ago though and I'm not sure adding examples will even increase adoption.

**Comment by goodmorninggoaway** [comment]
I'm sure I'm doing something wrong - not seeing the infrastructure navs

**Comment by goodmorninggoaway** [comment]
I ran `node ./create-react-infosight-microapp/packages/create-react-app hello-world-microapp` expecting it to use the local template. Since I don't feel like thinking anymore, how do you test it?

**Comment by coltonw** [comment]
I run `REACT_APP_MICROAPP_ID=sample npm run start` from the base directory to run the template directly.  I have not retested actually creating the app again in a while and so it would take some time for me to figure out how to do that.

**Comment by coltonw** [comment]
Ok, so I tested it as creating the entire microapp by running `yarn create-react-app sample` from the base directory.

**Comment by goodmorninggoaway** [comment]
> Ok, so I tested it as creating the entire microapp by running `yarn create-react-app sample` from the base directory.

```
➜  create-react-infosight-microapp git:(addProductInterface) ✗  yarn create-react-app sample
yarn run v1.15.2
$ node tasks/cra.js sample

-------------------------------------------------------
Assuming you have already run `yarn` to update the deps.
If not, remember to do this before testing!
-------------------------------------------------------

Please commit your changes before running this script!
Exiting because `git status` is not empty:

?? portal-sample-frontend/
?? yarn.lock


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  create-react-infosight-microapp git:(addProductInterface) ✗  cd ..
➜  code  cd create-react-infosight-microapp/packages/react-scripts
➜  react-scripts git:(addProductInterface) ✗  yarn create-react-app sample
yarn run v1.15.2
$ /Users/mdavis/code/create-react-infosight-microapp/node_modules/.bin/create-react-app sample

Creating a new Microapp @infosight/portal-sample-frontend in /Users/mdavis/code/create-react-infosight-microapp/packages/react-scripts/portal-sample-frontend.

warning package.json: No license field
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and @infosight/microapp-scripts...

warning package.json: No license field
warning @infosight/portal-sample-frontend@1.0.0: No license field
[1/4] 🔍  Resolving packages...
warning @infosight/microapp-scripts > fsevents@1.2.4: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @infosight/microapp-scripts > react-app-polyfill > core-js@2.5.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @infosight/microapp-scripts > workbox-webpack-plugin > workbox-build > joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning @infosight/microapp-scripts > webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @infosight/microapp-scripts > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning @infosight/microapp-scripts > jest > jest-cli > jest-config > babel-core > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @infosight/microapp-scripts > jest > jest-cli > jest-haste-map > sane > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @infosight/microapp-scripts > jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning @infosight/microapp-scripts > workbox-webpack-plugin > workbox-build > joi > topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning @infosight/microapp-scripts > workbox-webpack-plugin > workbox-build > joi > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning @infosight/microapp-scripts > workbox-webpack-plugin > workbox-build > joi > topo > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning @infosight/microapp-scripts > @svgr/webpack > @svgr/core > h2x-core > h2x-parse > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error An unexpected error occurred: "https://registry.yarnpkg.com/@infosight%2fshell-api: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mdavis/code/create-react-infosight-microapp/packages/react-scripts/portal-sample-frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom @infosight/microapp-scripts @infosight/shell-api @infosight/elmer classnames@2.2.5 history@4.7.2 moment@2.22.2 moment-timezone@0.5.20 numeral@2.0.6 object-hash@1.1.5 prop-types@15.5.8 react-autobind react-redux react-router@4.2.0 react-router-dom@4.2.2 redux redux-devtools-extension redux-thunk styled-components@3.3.3 underscore urijs --cwd /Users/mdavis/code/create-react-infosight-microapp/packages/react-scripts/portal-sample-frontend has failed.

Deleting generated file... package.json
Deleting generated file... yarn.lock
Done.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  react-scripts git:(addProductInterface) ✗  pwd
/Users/mdavis/code/create-react-infosight-microapp/packages/react-scripts
➜  react-scripts git:(addProductInterface) ✗  D
```

**Review by goodmorninggoaway — APPROVED** [review]

**Pull request merged**
